config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'users#new', as: :new_user
  post '/auth/steam/callback' => 'users#oauth_callback', as: :oauth_callback
  delete '/logout' => 'users#logout', as: :logout

  get '/games' => 'users#games', as: :user_games
  get '/games/:id' => 'users#games'

  root to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # TODO break out into Steam::User or something
  def self.get_all_steam_games
    Rails.logger.debug "User#get_all_steam_games ..."
    Rails.cache.fetch('all_steam_games', expires: 1.day) {
      all_games = Steam::Apps.get_all # 75k+ records like {'appid'=>'...', 'name'=>'...'}
      all_games_by_id = {} # 75k+ is too big to use one Hash[*games.map{...}] call
      all_games.each{|a| all_games_by_id[a['appid']] = a['name'] }
      all_games_by_id
    }
  end

  def self.get_steam_games(username)
    Rails.logger.debug "User#get_steam_games(#{username.inspect}) ..."
    id = Steam::User.vanity_to_steamid(username)
    result = Steam::Player.owned_games(id)
    games = result['games']
    if result['game_count'] != games.length
      raise "Uh oh, Steam 'game_count' and our @games array's length don't match"
    end
    return games
  end

  def self.sort_steam_games(games)
    Rails.logger.debug "User#sort_steam_games ..."
    all_games_by_id = get_all_steam_games
    sorted_games = {}
    games.each do |game|
      game_name = all_games_by_id[game['appid']]
      sorted_games[game_name] = game['playtime_forever']
    end
    return sorted_games
  end


private

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.login = auth.info.nickname
      user.info = auth.info
      user.raw_info = auth.raw_info
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    session[:user_id].present?
  end
  helper_method :logged_in?

  def current_user
    return nil unless logged_in?
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user

  def require_login
    if !logged_in?
      render plain: "Access denied", status: 404
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :verify_authenticity_token, only: :oauth_callback
  before_action :require_login, only: :games

  def new
  end

  def oauth_callback
    logger.debug params.to_unsafe_h.inspect
    logger.debug auth_hash.inspect

    user = User.from_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url, notice: "Logged in as #{user.login}"

  rescue OmniAuth::Error => e
    flash[:error] = "Error during OAuth: #{e}"
    render :new
  end

  def games
    # FIXME move all this logic into not-a-controller
    username = params[:id] || current_user.login

    @games = User.get_steam_games(username)
    @sorted_games = User.sort_steam_games(@games)
    @total_hours = @sorted_games.inject(0){|t,game| t += game[1] }

    @games = games
  end


private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steamchain</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.present? -%>
      <p>Flash: <%= flash.to_h.inspect %></p>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/users/games.html.erb
<p>You own <%= @games.length %> games

<p><%= @total_hours/60 %> total hours played

<ul>
  <% my_games.sort_by{|k,v| v}.each do |game,minutes| -%>
    <%= "#{game}: #{(minutes/60.0).round(1)} hours" %>
  <% end -%>
</ul>

app/views/users/new.html.erb
<!-- ethers.js -->
<script charset="utf-8"
        src="https://cdn.ethers.io/scripts/ethers-v4.min.js"
        type="text/javascript">
</script>


<%# FIXME how do we see omniauth routes? %>
<% if logged_in? %>
  <p>1. Great! You're logged in as <strong><%= current_user.login %></strong>.
    <%= link_to 'View your games', user_games_path %>
<% else -%>
  <p>1. <%= link_to 'Connect to Steam', '/auth/steam' %>
<% end -%>

<p>2. [Sign transaction]

<p>3. You're on the chain now baby